-- Generated by Prelude Config Generator
-- Table: fixture

CREATE TABLE IF NOT EXISTS fixture (
  id VARCHAR(50),
  source VARCHAR(50),
  corpus VARCHAR(50),
  fixture_set_version VARCHAR(50),
  introspection_commit VARCHAR(50),
  index_commit VARCHAR(50),
  author VARCHAR(50),
  date_authored DATE,
  filter_complexity VARCHAR(50),
  schema_reach VARCHAR(50),
  requires_aggregation BOOLEAN,
  feasible BOOLEAN,
  catalogues VARCHAR(50),
  negative_reason VARCHAR(50),
  prompt VARCHAR(171),
  reference_sqon VARCHAR(342),
  reference_ast VARCHAR(342),
  reference_fields VARCHAR(195),
  reference_aggregation VARCHAR(134),
  expected_record_ids VARCHAR(50),
  reference_validated VARCHAR(50),
  frontier_pass VARCHAR(50),
  frontier_model VARCHAR(255),
  validation_date VARCHAR(255),
  notes VARCHAR(284),
  submission_metadata JSONB
);

DROP INDEX IF EXISTS idx_fixture_submission_id;
CREATE UNIQUE INDEX IF NOT EXISTS idx_fixture_submission_id
  ON fixture ((submission_metadata->>'submission_id'));