// global/utils/dataTablesDiscovery.ts
import fs from 'fs';
import path from 'path';
import { getTableConfig } from './tableConfig';

export interface DataTableInfo {
	id: string;
	title: string;
	path: string;
}

/**
 * Discovers data tables by scanning the pages directory for dataTable* folders.
 *
 * Updated for new architecture:
 * - Now scans pages/ directory instead of components/pages/activeDataTables
 * - Looks for folders matching pattern: dataTable*
 * - Works with the refactored structure where config lives in pages/
 *
 * Learning Note: File System Operations in Next.js API Routes
 * - fs module only works server-side (Node.js)
 * - process.cwd() gives the root directory of the project
 * - path.join() safely creates cross-platform file paths
 */
export function discoverDataTables(): DataTableInfo[] {
	try {
		/**
		 * Updated path: Now points to pages/ directory
		 * This matches our new architecture where data table pages live in pages/dataTable*
		 */
		const pagesPath = path.join(process.cwd(), 'pages');

		// Check if directory exists
		if (!fs.existsSync(pagesPath)) {
			console.warn('Pages directory not found:', pagesPath);
			return [];
		}

		/**
		 * Read all entries in pages directory
		 * withFileTypes: true gives us Dirent objects (includes isDirectory() method)
		 */
		const entries = fs.readdirSync(pagesPath, { withFileTypes: true });

		/**
		 * Filter for directories that match our data table naming pattern.
		 *
		 * Supports two patterns:
		 * - *Table suffix: correlationTable, mutationTable, expressionTable, proteinTable
		 * - dataTable* prefix: dataTableOne (legacy, kept for backwards compatibility)
		 */
		const dataTableDirs = entries.filter(
			(entry) =>
				entry.isDirectory() &&
				// fixtureTable has its own dedicated navbar item, so exclude it from the Explore Data dropdown
				entry.name !== 'fixtureTable' &&
				(entry.name.endsWith('Table') || entry.name.startsWith('dataTable')),
		);

		/**
		 * Convert directory names to DataTableInfo objects.
		 *
		 * Priority order for display names:
		 * 1. Environment variable (e.g., NEXT_PUBLIC_CORRELATION_TABLE_NAME)
		 * 2. tableConfig.ts configuration
		 * 3. Auto-generated from folder name
		 */
		return dataTableDirs.map((dir) => {
			const envKeyBase = dir.name
				.replace(/([A-Z])/g, '_$1')
				.toUpperCase()
				.replace(/^_/, '');

			const envDisplayName = process.env[`NEXT_PUBLIC_${envKeyBase}_NAME`];
			const customConfig = getTableConfig(dir.name);

			const autoGeneratedTitle = dir.name
				.replace(/([A-Z])/g, ' $1')
				.replace(/^./, (str) => str.toUpperCase())
				.trim();

			const urlPath = `/${dir.name}`;

			return {
				id: dir.name,
				title: envDisplayName || customConfig?.displayName || autoGeneratedTitle,
				path: urlPath,
			};
		});
	} catch (error) {
		console.error('Error discovering data tables:', error);
		return [];
	}
}
