import { inferPgType } from './inferTypes';
import { ParsedCsv } from './csvParser';

function sanitizeName(name: string): string {
	return name
		.toLowerCase()
		.replace(/\s+/g, '_')
		.replace(/[^a-z0-9_]/g, '');
}

export function generatePostgresSql(csv: ParsedCsv, tableName: string): string {
	const table = sanitizeName(tableName);

	const columnValues: Record<string, string[]> = {};
	csv.headers.forEach((h) => {
		columnValues[h] = [];
	});
	csv.rows.forEach((row) => {
		csv.headers.forEach((h, i) => {
			columnValues[h].push(row[i] ?? '');
		});
	});

	const columns = csv.headers
		.map((header) => {
			const col = sanitizeName(header);
			const type = inferPgType(columnValues[header]);
			return `  ${col} ${type}`;
		})
		.join(',\n');

	return [
		`-- Generated by Prelude Config Generator`,
		`-- Table: ${table}`,
		``,
		`CREATE TABLE IF NOT EXISTS ${table} (`,
		columns + ',',
		`  submission_metadata JSONB`,
		`);`,
		``,
		`DROP INDEX IF EXISTS idx_${table}_submission_id;`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_${table}_submission_id`,
		`  ON ${table} ((submission_metadata->>'submission_id'));`,
	].join('\n');
}
